// Default tracker configuration seeded for a user the first time their config
// is requested. Mirrors the frontend defaults in src/config/trackerDefaults.ts.
export const defaultConfig = {
    applicationTypes: [
        {
            id: "transfer-in",
            name: "Transfer In",
            color: "teal",
            documents: [
                "Application Form",
                "Application Fee",
                "Passport",
                "Visa",
                "I-94",
                "Transfer Request Form",
                "I-20",
                "Bank Statement",
                "Financial Support Letter",
                "Trascript",
                "Credentials",
                "Essay",
                "Test",
                "Acceptance Letter",
                "Enrollment Agreement",
            ],
        },
        {
            id: "abroad-approved",
            name: "Abroad Approved",
            color: "lime",
            documents: ["Visa", "I-94", "Enrollment Agreement"],
        },
        {
            id: "COS-approved",
            name: "COS Approved",
            color: "amber",
            documents: ["Approval Notice", "Enrollment Agreement"],
        },
        {
            id: "COEL",
            name: "COEL",
            color: "cyan",
            documents: [
                "Application Form",
                "Passport",
                "Bank Statement",
                "Financial Support Letter",
                "Essay",
                "Test",
                "Acceptance Letter",
                "Enrollment Agreement",
            ],
        },
        {
            id: "domestic",
            name: "Domestic",
            color: "orange",
            documents: [
                "Application Form",
                "Application Fee",
                "ID",
                "Credentials",
                "Essay",
                "Test",
                "Acceptance Letter",
                "Enrollment Agreement",
            ],
        },
        {
            id: "reinstatement",
            name: "Reinstatement",
            color: "pink",
            documents: [
                "Application Form",
                "Application Fee",
                "Passport",
                "Visa",
                "I-94",
                "Transfer Request Form",
                "I-20",
                "Bank Statement",
                "Financial Support Letter",
                "Transcripts",
                "Credentials",
                "Foreign Address Form",
                "High School Attestation Form",
                "I-539 / G-28",
                "Explanation Letter",
                "Essay",
                "Test",
                "Tution",
                "Acceptance Letter",
                "Enrollment Agreement",
            ],
        },
        {
            id: "abroad",
            name: "Abroad",
            color: "indigo",
            documents: [
                "Application Form",
                "Application Fee",
                "Passport",
                "Bank Statement",
                "Financial Support Letter",
                "Credentials",
                "Foreign Address Form",
                "High School Attestation Form",
                "Essay",
                "Placement Test",
                "Acceptance Letter",
            ],
        },
        {
            id: "COS",
            name: "COS",
            color: "blue",
            documents: [
                "Application Form",
                "Application Fee",
                "Passport",
                "Visa",
                "I-94",
                "I-20 / DS-2019",
                "Bank Statement",
                "Financial Support Letter",
                "Credentials",
                "Foreign Address Form",
                "High School Attestation Form",
                "I-539 / G-28",
                "Explanation Letter",
                "Essay",
                "Test",
                "Acceptance Letter",
            ],
        },
    ],
    terms: ["Fall 2025", "Winter 2026", "Spring 2026"],
    programs: [
        "English as a Second Language",
        "Professional English",
        "English for Academic Purposes",
        "English for Healthcare",
        "AAS in Business",
        "AAS in Marketing",
        "AAS in Accounting",
        "AAS in Information Technology",
    ],
    schedules: ["4 Day - Morning", "2 Day - Morning", "3 Day - Evening"],
};
